"""Phase 7 Track B — Telegram operator surface.

Thin façade over python-telegram-bot. The real network entrypoint
(`bot.py`) is built last; this package is designed so every unit test
can drive fake `Update` objects through `dispatch` without any
network I/O — per `docs/PLAN_PHASE_7_TELEGRAM.md` §4.3.
"""
from __future__ import annotations

from .auth import AuthDecision, Authorizer, DenyReason
from .bot import (
    MAX_TELEGRAM_CHARS,
    AsyncioSubprocessRunner,
    build_application,
    build_chat_pipeline,
    build_dispatcher,
    build_long_running_runner,
    route_chat,
    route_command,
)
from .dispatch import (
    Dispatcher,
    DispatchOutcome,
    Handler,
    IncomingMessage,
    OutcomeKind,
    ParsedCommand,
    parse_command,
)
from .formatters import (
    DEFAULT_DECISIONS_TAIL,
    MAX_DECISIONS_TAIL,
    MAX_LOG_LINE_CHARS,
    MAX_PENDING_ROWS,
    MAX_VAULT_BODY_CHARS,
    MAX_VERBATIM_CHARS,
    pending_proposals,
    render_decision_idempotent,
    render_decision_recorded,
    render_decisions,
    render_help,
    render_logs,
    render_pending,
    render_proposal,
    render_status,
    render_system_info,
    render_vault_note,
    render_vault_reindex,
    render_vault_sources,
    render_vault_status,
    render_verbatim,
)
from .handlers import (
    DEFAULT_COMMAND_HELP,
    Clock,
    ColdRefResolver,
    VaultState,
    approve_handler,
    build_read_only_handlers,
    build_write_handlers,
    decisions_handler,
    defer_handler,
    help_descriptions_for,
    help_handler,
    logs_handler,
    pending_handler,
    proposal_handler,
    recall_handler,
    reject_handler,
    status_handler,
    vault_handler,
)
from .logs import DEFAULT_LOG_LINES, MAX_LOG_LINES, tail_events
from .long_running import (
    MAX_LONG_RUNNING_CHARS,
    InFlightRegistry,
    LongRunningRunner,
    SubprocessRunner,
)
from .restart import reexec_in_place
from .status import StatusSnapshot, SystemInfo, collect_system_info, compute_status

__all__ = [
    "DEFAULT_COMMAND_HELP",
    "DEFAULT_DECISIONS_TAIL",
    "DEFAULT_LOG_LINES",
    "MAX_DECISIONS_TAIL",
    "MAX_LOG_LINES",
    "MAX_LOG_LINE_CHARS",
    "MAX_LONG_RUNNING_CHARS",
    "MAX_PENDING_ROWS",
    "MAX_TELEGRAM_CHARS",
    "MAX_VAULT_BODY_CHARS",
    "MAX_VERBATIM_CHARS",
    "AsyncioSubprocessRunner",
    "AuthDecision",
    "Authorizer",
    "Clock",
    "ColdRefResolver",
    "DenyReason",
    "DispatchOutcome",
    "Dispatcher",
    "Handler",
    "InFlightRegistry",
    "IncomingMessage",
    "LongRunningRunner",
    "OutcomeKind",
    "ParsedCommand",
    "StatusSnapshot",
    "SubprocessRunner",
    "SystemInfo",
    "VaultState",
    "approve_handler",
    "build_application",
    "build_chat_pipeline",
    "build_dispatcher",
    "build_long_running_runner",
    "build_read_only_handlers",
    "build_write_handlers",
    "collect_system_info",
    "compute_status",
    "decisions_handler",
    "defer_handler",
    "help_descriptions_for",
    "help_handler",
    "logs_handler",
    "parse_command",
    "pending_handler",
    "pending_proposals",
    "proposal_handler",
    "recall_handler",
    "reexec_in_place",
    "reject_handler",
    "render_decision_idempotent",
    "render_decision_recorded",
    "render_decisions",
    "render_help",
    "render_logs",
    "render_pending",
    "render_proposal",
    "render_status",
    "render_system_info",
    "render_vault_note",
    "render_vault_reindex",
    "render_vault_sources",
    "render_vault_status",
    "render_verbatim",
    "route_chat",
    "route_command",
    "status_handler",
    "tail_events",
    "vault_handler",
]
